//
//  CommentsInteractorTests.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 08/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceholderapp
import XCTest

class CommentsInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CommentsInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupCommentsInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCommentsInteractor() {
        sut = CommentsInteractor()
    }
    
    // MARK: Test doubles
    
    class CommentsPresentationLogicSpy: CommentsPresentationLogic {
        
        var setupViewCalled = false
        
        func setupView() {
            setupViewCalled = true
        }
    }
    
    // MARK: Tests
    
    func testSetupView() {
        // Given
        let spy = CommentsPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        sut.setupView()
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "setupView() should ask the presenter to format the result")
    }
}
