//
//  CommentsPresenterTests.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 08/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceholderapp
import XCTest

class CommentsPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CommentsPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupCommentsPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCommentsPresenter() {
        sut = CommentsPresenter()
    }
    
    // MARK: Test doubles
    
    class CommentsDisplayLogicSpy: CommentsDisplayLogic {
        
        var setupViewCalled = false
        
        func setupView() {
            setupViewCalled = true
        }
    }
    
    // MARK: Tests
    
    func testSetupView() {
        // Given
        let spy = CommentsDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.setupView()
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "setupView() should ask the view controller to display the result")
    }
}
