//
//  CommentsInteractor.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 07/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentsBusinessLogic {
}

protocol CommentsDataStore {
    var comments: [Comment]? { get set }
}

class CommentsInteractor: CommentsBusinessLogic, CommentsDataStore {
    
    var presenter: CommentsPresentationLogic?
    var worker: CommentsWorker?
    
    var comments: [Comment]?
}
