//
//  CommentsRouter.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 07/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CommentsRoutingLogic {
}

protocol CommentsDataPassing {
    var dataStore: CommentsDataStore? { get }
}

class CommentsRouter: NSObject, CommentsRoutingLogic, CommentsDataPassing {
    weak var viewController: CommentsViewController?
    var dataStore: CommentsDataStore?
}
