//
//  ExploreWorkerTests.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 08/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceholderapp
import XCTest

class ExploreWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ExploreWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupExploreWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupExploreWorker() {
        sut = ExploreWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
}
