//
//  ProfileInteractor.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 06/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
    func setupView()
}

protocol ProfileDataStore {
    var user: User? { get set }
    var albums: [Album]? { get set }
    var todos: [Todo]? { get set }
}

class ProfileInteractor: ProfileBusinessLogic, ProfileDataStore {

    var presenter: ProfilePresentationLogic?
    var worker: ProfileWorker?
    
    var user: User?
    var albums: [Album]?
    var todos: [Todo]?
    
    func setupView() {
        let response = Profile.Models.Response(user: user)
        presenter?.setupView(response: response)
    }
    
}
