//
//  ProfileWorker.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 06/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProfileWorker {
    
    func getPhotos(for album: Album, completion: @escaping([Photo]?, String?) -> Void) {
        
        // LETS and VARS
        let photosRepository = PhotoRepository()
        
        // Get Photos
        photosRepository.getPhotos(for: album) { (photos) in
            print(photos)
            completion(photos, nil)
        }
    }
    
}
