//
//  ProfileModels.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 06/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Event: String {
    case onTouchAlbums
    case onTouchTodos
}

enum Profile {
    // MARK: Use cases
    
    enum Models {
        struct Request {
            var event: Event?
        }
        struct Response {
            var user: User?
            var photos: [Photo]?
        }
        struct ViewModel {
            var name: String?
            var username: String?
            var avatar: UIImage?
            var website: String?
        }
        struct AlbumCellModel {
            var album: Album?
        }
        struct TodoCellModel {
            var todo: Todo?
        }
    }
}
