//
//  ProfileRouter.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 06/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProfileRoutingLogic {
    func routeToPhotos(segue: UIStoryboardSegue?)
}

protocol ProfileDataPassing {
    var dataStore: ProfileDataStore? { get }
}

class ProfileRouter: NSObject, ProfileRoutingLogic, ProfileDataPassing {
    weak var viewController: ProfileViewController?
    var dataStore: ProfileDataStore?
    
    // MARK: Routing
    
    func routeToPhotos(segue: UIStoryboardSegue?) {
        
        let storyboard = UIStoryboard(name: Constants.Storyboard.photos, bundle: nil)
        
        if let segue = segue, let destinationVC = segue.destination as? PhotosViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToPhotos(source: dataStore, destination: &destinationDS)
        } else if let destinationVC = storyboard.instantiateInitialViewController() as? PhotosViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToPhotos(source: dataStore, destination: &destinationDS)
            navigateToPhotos(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToPhotos(source: ProfileViewController, destination: PhotosViewController) {
        ui {
            source.present(destination, animated: true)
        }
    }
    
    // MARK: Passing data
    
    func passDataToPhotos(source: ProfileDataStore?, destination: inout PhotosDataStore?) {
        destination?.photos = source?.photos
    }
}
