//
//  PhotosViewControllerTests.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 08/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceholderapp
import XCTest

class PhotosViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PhotosViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupPhotosViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPhotosViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "PhotosViewController") as! PhotosViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class PhotosBusinessLogicSpy: PhotosBusinessLogic {
        
        var setupViewCalled = false
        var getPhotosCountCalled = false
        var getPhotoCellForCalled = false
        
        func setupView() {
            setupViewCalled = true
        }
        
        func getPhotosCount() -> Int {
            getPhotosCountCalled = true
            return 10
        }
        
        func getPhotoCellFor(index: Int) -> Photos.Models.PhotoCellModel {
            getPhotoCellForCalled = true
            return Photos.Models.PhotoCellModel()
        }
    }
    
    // MARK: Tests
}
