//
//  PhotosInteractorTests.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 08/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import JSONPlaceholderapp
import XCTest

class PhotosInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PhotosInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupPhotosInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPhotosInteractor() {
        sut = PhotosInteractor()
    }
    
    // MARK: Test doubles
    
    class PhotosPresentationLogicSpy: PhotosPresentationLogic {
        
        var setupViewCalled = false
        
        func setupView() {
            setupViewCalled = true
        }
    }
    
    // MARK: Tests
    
    func testSetupView() {
        // Given
        let spy = PhotosPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        sut.setupView()
        
        // Then
        XCTAssertTrue(spy.setupViewCalled, "setupView() should ask the presenter to format the result")
    }
    
    func testGetPhotosCount() {
        // Given
        let spy = PhotosPresentationLogicSpy()
        sut.presenter = spy
        sut.photos = [Photo()]
        
        // When
        let count = sut.getPhotosCount()
        
        // Then
        XCTAssertEqual(sut.photos?.count, count, "setupView() should ask the presenter to format the result")
    }
    
    func testGetPhotoCellFor() {
        //TODO
    }
}
