//
//  ExploreWorker.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 04/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ExploreWorker {
    
    func getAlbumsAndTodos(for user: User, completion: @escaping([Album]?, [Todo]?, String?) -> Void) {
        
        // LETS and VARS
        var mAlbums: [Album]?
        var mTodos: [Todo]?
        
        let dispatchGroup = DispatchGroup()
        
        let albumRepository = AlbumRepository()
        let todoRepository = TodoRepository()
        
        
        // Get Albums
        dispatchGroup.enter()
        albumRepository.getAlbums(for: user) { (albums) in
            print(albums)
            mAlbums = albums
            dispatchGroup.leave()
        }
        
        // Get Todos
        dispatchGroup.enter()
        todoRepository.getTodos(for: user) { (todos) in
            print(todos)
            mTodos = todos
            dispatchGroup.leave()
        }

        // DispatchGroup
        dispatchGroup.notify(queue: .main) {
            completion(mAlbums, mTodos, nil)
        }
    }
}
