//
//  ExploreRouter.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 04/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ExploreRoutingLogic {
    func routeToProfile(segue: UIStoryboardSegue?)
}

protocol ExploreDataPassing {
    var dataStore: ExploreDataStore? { get }
}

class ExploreRouter: NSObject, ExploreRoutingLogic, ExploreDataPassing {
    
    weak var viewController: ExploreViewController?
    var dataStore: ExploreDataStore?
    
    // MARK: Routing
    
    func routeToProfile(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ProfileViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToProfile(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "ProfileStoryboard", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProfileViewController") as! ProfileViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToProfile(source: dataStore!, destination: &destinationDS)
            navigateToProfile(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToProfile(source: ExploreViewController, destination: ProfileViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToProfile(source: ExploreDataStore, destination: inout ProfileDataStore) {
//        destination.name = source.name
    }
}
