//
//  ExploreModels.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 04/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Explore {
    // MARK: Use cases
    
    enum Models {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
        struct UserCellModel {
            var user: User?
        }
    }
}
