//
//  PhotosSceneInteractor.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 07/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosSceneBusinessLogic
{
  func doSomething(request: PhotosScene.Something.Request)
}

protocol PhotosSceneDataStore
{
  //var name: String { get set }
}

class PhotosSceneInteractor: PhotosSceneBusinessLogic, PhotosSceneDataStore
{
  var presenter: PhotosScenePresentationLogic?
  var worker: PhotosSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PhotosScene.Something.Request)
  {
    worker = PhotosSceneWorker()
    worker?.doSomeWork()
    
    let response = PhotosScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
