//
//  PhotosInteractor.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 07/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosBusinessLogic {
    func setupView()
    func getPhotosCount() -> Int
    func getPhotoCellFor(index: Int) -> Photos.Models.PhotoCellModel
}

protocol PhotosDataStore {
    var photos: [Photo]? { get set }
}

class PhotosInteractor: PhotosBusinessLogic, PhotosDataStore {
    var presenter: PhotosPresentationLogic?
    var worker: PhotosWorker?
    
     var photos: [Photo]?
    
    func setupView() {
        presenter?.setupView()
    }
    
    func getPhotosCount() -> Int {
        return photos?.count ?? 0
    }
    
    func getPhotoCellFor(index: Int) -> Photos.Models.PhotoCellModel {
        guard let photo = photos?.getElement(index) else { return Photos.Models.PhotoCellModel() }
        return Photos.Models.PhotoCellModel(photo: photo)
    }
    
    
}
