//
//  PhotosRouter.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 07/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhotosRoutingLogic {
}

protocol PhotosDataPassing {
    var dataStore: PhotosDataStore? { get }
}

class PhotosRouter: NSObject, PhotosRoutingLogic, PhotosDataPassing {
    weak var viewController: PhotosViewController?
    var dataStore: PhotosDataStore?
}

