//
//  FeedViewController.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 04/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FeedDisplayLogic: class {
    func setupView(viewModel: Feed.Models.ViewModel)
    func displayPosts(viewModel: Feed.Models.ViewModel)
}

class FeedViewController: BaseViewController, FeedDisplayLogic {
    
    var interactor: FeedBusinessLogic?
    var router: (NSObjectProtocol & FeedRoutingLogic & FeedDataPassing)?
    
    // MARK: IBOutlets
    @IBOutlet weak var feedTableView: UITableView!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = FeedInteractor()
        let presenter = FeedPresenter()
        let router = FeedRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor        
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        if let parent = parent?.parent as? MainViewController {
            parent.mainDelegate = self
        }
        
        interactor?.setupView()
    }
    
    /// setup and customize the UI elements in the scene
    func setupView(viewModel: Feed.Models.ViewModel) {
        
        // NavigationController
        self.navigationItem.title = "feed".localized;
        
        // TableView
        feedTableView.register(FeedTableViewCell.cellIdentifier)
        feedTableView.delegate = self
        feedTableView.dataSource = self
    }
    
    func displayPosts(viewModel: Feed.Models.ViewModel) {
        
        print(viewModel)
        
        reloadData()
    }
    
    func reloadData() {
        ui { [weak self] in
            self?.feedTableView.reloadData()
        }
    }
}

// MARK: UITableviewDelegate and UITableViewDataSource

extension FeedViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return interactor?.getPostsCount() ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        guard let cell = tableView.dequeueReusableCell(withIdentifier: FeedTableViewCell.cellIdentifier) as? FeedTableViewCell else {
            print("Error to cast TableViewCell to FeedTableViewCell")
            return UITableViewCell()
        }
        
        guard let data = interactor?.getPostCellFor(index: indexPath.row) else {
            print("Error to get PostCellModel from index")
            return UITableViewCell()
        }
        
        cell.updateUI(model: data)
        
        return cell
    }
}


// MARK: MainDelegate

extension FeedViewController: MainDelegate {
   
    func fetchedPosts(posts: [Post]) {
        reloadData()
    }
}
