//
//  FeedRouter.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 04/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FeedRoutingLogic {
    func routeToComments(segue: UIStoryboardSegue?)
}

protocol FeedDataPassing {
    var dataStore: FeedDataStore? { get }
}

class FeedRouter: NSObject, FeedRoutingLogic, FeedDataPassing {
    weak var viewController: FeedViewController?
    var dataStore: FeedDataStore?
    
    // MARK: Routing
    
    func routeToComments(segue: UIStoryboardSegue?) {
        
        let storyboard = UIStoryboard(name: Constants.Storyboard.comments, bundle: nil)
        
        if let segue = segue, let destinationVC = segue.destination as? CommentsViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToComments(source: dataStore, destination: &destinationDS)
        } else if let destinationVC = storyboard.instantiateInitialViewController() as? CommentsViewController {
            var destinationDS = destinationVC.router?.dataStore
            passDataToComments(source: dataStore, destination: &destinationDS)
            navigateToComments(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToComments(source: FeedViewController, destination: CommentsViewController) {
        ui {
            source.present(destination, animated: true)
        }
    }
    
    // MARK: Passing data
    
    func passDataToComments(source: FeedDataStore?, destination: inout CommentsDataStore?) {
        destination?.comments = source?.comments
    }
}
