//
//  FeedPresenter.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 04/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FeedPresentationLogic {
    func setupView(response: Feed.Models.Response)
    func presentAllPosts(response: Feed.Models.Response)
}

class FeedPresenter: FeedPresentationLogic {
    
    weak var viewController: FeedDisplayLogic?
    
    func setupView(response: Feed.Models.Response) {
        let viewModel = Feed.Models.ViewModel()
        viewController?.setupView(viewModel: viewModel)
    }
    
    func presentAllPosts(response: Feed.Models.Response) {
        var viewModel = Feed.Models.ViewModel()
        viewModel.posts = response.posts
        viewController?.displayPosts(viewModel: viewModel)
    }
}
