//
//  FeedWorker.swift
//  JSONPlaceholderapp
//
//  Created by Iván Díaz Molina on 04/06/2020.
//  Copyright (c) 2020 Iván Díaz Molina. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FeedWorker {
    
    func getComments(for post: Post, completion: @escaping([Comment]?, String?) -> Void) {
        
        // LETS and VARS
        let commentsRepository = CommentRepository()
        
        // Get Comments
        commentsRepository.getComments(for: post) { (comments) in
            print(comments)
            completion(comments, nil)
        }
    }
}
